import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TakeAway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="container py-10">
          {/* <div className="vertical-guides">
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
            <div className="vertical-guide" />
          </div> */}

          {children}</main>
      </body>
    </html>
  );
}
